#!/usr/bin/env python3
"""Report the review status of every wiki page.

A page that finished a full review pass carries `reviewed:` front
matter (see CONTRIBUTING.md, "Review stamps"). This script reads the
front matter of every page and prints two lists: pages with their
review dates, and pages still waiting for a pass. The stamp is the
only record — the script keeps no state of its own, so it can never
disagree with the pages.

Run from the repository root:

    python3 contrib/review-status.py
"""

from pathlib import Path

DOCS = Path(__file__).resolve().parent.parent / "docs"

# Generated by the site repo (npm run sync:wiki); never hand-edited.
GENERATED = {"releases/changelog.md"}
# Supporting files that are not published pages.
NOT_PAGES = {"assets/settings/README.md"}
SKIP = GENERATED | NOT_PAGES
# Directories that hold partials and assets, not pages.
SKIP_DIRS = ("assets", "includes")


def review_date(page):
    """Return the `reviewed:` value from front matter, or None."""
    lines = page.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    for line in lines[1:]:
        if line.strip() == "---":
            return None
        if line.startswith("reviewed:"):
            return line.split(":", 1)[1].strip()
    return None


def all_pages():
    """Every published page, as a path relative to docs/, sorted."""
    pages = []
    for path in DOCS.rglob("*.md"):
        rel = path.relative_to(DOCS).as_posix()
        if rel in SKIP or rel.split("/")[0] in SKIP_DIRS:
            continue
        pages.append(rel)
    return sorted(pages)


def main():
    pages = all_pages()
    stamped = {rel: date for rel in pages if (date := review_date(DOCS / rel))}

    print(f"{len(stamped)} of {len(pages)} pages carry a review stamp\n")

    print("Reviewed (oldest pass first):")
    for rel in sorted(stamped, key=lambda r: (stamped[r], r)):
        print(f"  {stamped[rel]}  {rel}")

    unstamped = [rel for rel in pages if rel not in stamped]
    print(f"\nWaiting for a pass ({len(unstamped)}):")
    sections = {}
    for rel in unstamped:
        name = rel.split("/")[0] if "/" in rel else "(root)"
        sections.setdefault(name, []).append(rel)
    for name, rels in sorted(sections.items()):
        label = name if name == "(root)" else name + "/"
        print(f"  {label} ({len(rels)})")
        for rel in rels:
            print(f"    {rel}")


if __name__ == "__main__":
    main()
